import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

const Resin: NextPage = () => {
  const [resin, setResin] = useState(0);
  const [CurrResin, setCurrResin] = useState(0);
  const [time, setTime] = useState(new Date());

  useEffect(() => {
    setResin(160 - CurrResin);
  }, [CurrResin]);

  return (
    <>
      <Head>
        <title>Resin Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="mx-4 flex h-16 justify-between">
          <Link
            href={"sanity"}
            className="flex h-full items-center rounded-lg bg-blue-700 px-5 font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Resin
          </Link>
          <Link
            href={"resin"}
            className="flex h-full items-center rounded-lg bg-blue-700 px-5 font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Resin
          </Link>
        </div>
        <div className="gap-12 px-4 py-16 text-center ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Resin Calculator
          </h1>
        </div>
        <div className="mx-4 flex flex-col gap-y-4">
          <label
            htmlFor="resin"
            className="mb-2 block font-medium text-gray-900 dark:text-white"
          >
            Resin
          </label>
          <input
            type="number"
            id="resin"
            min={0}
            max={160}
            className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
            required
            value={CurrResin}
            onChange={(e) => {
              if (Number(e.target.value) < 0) {
                setCurrResin(0);
              } else if (Number(e.target.value) > 160) {
                setCurrResin(160);
              } else {
                setCurrResin(Number(e.target.value));
              }
            }}
          />
          <div className="flex items-center ">
            <button
              type="button"
              className="w-2/12 rounded-lg bg-blue-700 px-5 py-6 font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
              onClick={() => {
                const customTimeMs = resin * 8 * 60 * 1000; // convert minutes to milliseconds
                const newTime = new Date(Date.now() + customTimeMs);
                setTime(newTime);
              }}
            >
              Calculate
            </button>
            <div className="ml-4  text-xs tracking-tight text-white sm:text-[5rem]">
              {resin} Resin {"\n"}
            </div>
          </div>
          <div className=" text-center tracking-tight text-white sm:text-[5rem] ">
            Will be full at:
            {CurrResin == 0 ? "" : ` ${time.toLocaleTimeString()}`}
          </div>
        </div>
      </main>
    </>
  );
};

export default Resin;
